# Generated by Django 2.1.7 on 2019-04-23 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_mua', models.IntegerField(default=0)),
                ('gia_ban', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_hoa_don',
            },
        ),
        migrations.CreateModel(
            name='HangDat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('check', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hang_dat',
            },
        ),
        migrations.CreateModel(
            name='HinhAnhSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.FileField(upload_to='product/')),
            ],
            options={
                'db_table': 'hinh_anh_san_pham',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach_hang', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(null=True)),
                ('sdt', models.CharField(max_length=200)),
                ('dia_chi', models.TextField()),
            ],
            options={
                'db_table': 'hoa_don',
            },
        ),
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.TextField()),
            ],
            options={
                'db_table': 'loai_hang',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.TextField()),
                ('sdt', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dia_chi', models.TextField(blank=True)),
                ('huyen', models.CharField(blank=True, max_length=255)),
                ('tinh', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('mo_ta', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nha_cung_cap',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.TextField()),
                ('ngay_them', models.DateField(auto_now_add=True)),
                ('gia_von', models.IntegerField(default=0)),
                ('gia_ban', models.IntegerField(default=0)),
                ('khuyen_mai', models.IntegerField(default=0)),
                ('so_luong', models.IntegerField(default=0)),
                ('ton_kho', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('mo_ta', models.TextField(blank=True)),
                ('avt', models.FileField(upload_to='product/avatar/')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('loai_hang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.LoaiHang')),
                ('nha_cung_cap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.NhaCungCap')),
            ],
            options={
                'db_table': 'san_pham',
            },
        ),
        migrations.CreateModel(
            name='SoQuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_thu', models.IntegerField(default=0)),
                ('tong_chi', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'so_quy',
            },
        ),
        migrations.CreateModel(
            name='TrangThaiHoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
            ],
            options={
                'db_table': 'trang_thai',
            },
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('ho_ten', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.IntegerField(default=1)),
                ('dia_chi', models.TextField(blank=True)),
                ('huyen', models.TextField(blank=True, max_length=255)),
                ('tinh', models.TextField(blank=True, max_length=255)),
                ('ngay_sinh', models.DateField(default=django.utils.timezone.now)),
                ('luong', models.IntegerField(default=0)),
                ('sdt', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('avatar', models.FileField(upload_to='users/')),
            ],
            options={
                'db_table': 'my_users',
            },
        ),
        migrations.AddField(
            model_name='hoadon',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khach_hang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_tao_hoa_don', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.TrangThaiHoaDon'),
        ),
        migrations.AddField(
            model_name='hinhanhsp',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='hangdat',
            name='hang_dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='hangdat',
            name='nguoi_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='hoa_don',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don', to='Store.HoaDon'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_pham_hoa_don', to='Store.SanPham'),
        ),
    ]
