# Generated by Django 2.1.7 on 2019-03-16 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/')),
                ('image_path', models.FilePathField()),
            ],
            options={
                'db_table': 'image_product',
            },
        ),
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.TextField(blank=True, max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.IntegerField(default=1)),
                ('last_name', models.TextField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('district', models.TextField(blank=True)),
                ('province', models.TextField(blank=True)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('salary', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'my_users',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.TextField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('prime_cost', models.IntegerField(default=0)),
                ('saleprice', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('inventory', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('RGV', 'Rau gia vị'), ('TC', 'Trái cây'), ('RAC', 'Rau ăn củ'), ('N', 'Nấm'), ('RAL', 'Rau ăn lá'), ('RCK', 'Các loại rau củ khác')], max_length=255)),
                ('describes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.Products'),
        ),
    ]
