# Generated by Django 2.1.7 on 2019-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_mua', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_hoa_don',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('don_gia_nhap', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_phieu_nhap',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuTra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_nhap_lai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_phieu_tra',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuTraHangNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('gia_tra_lai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_phieu_tra_hang_nhap',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuXuatHuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_phieu_xuat_huy',
            },
        ),
        migrations.CreateModel(
            name='HinhAnhSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.FileField(upload_to='product/')),
                ('duong_dan', models.FilePathField()),
            ],
            options={
                'db_table': 'hinh_anh_san_pham',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lap', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ghi_chu', models.TextField()),
                ('is_paid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'hoa_don',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.TextField()),
                ('sdt', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dia_chi', models.TextField(blank=True)),
                ('huyen', models.CharField(blank=True, max_length=255)),
                ('tinh', models.CharField(blank=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('mo_ta', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nha_cung_cap',
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_nhap', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phieu_nhap',
            },
        ),
        migrations.CreateModel(
            name='PhieuTra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tra', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phieu_tra_hang',
            },
        ),
        migrations.CreateModel(
            name='PhieuTraHangNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu', models.TextField()),
            ],
            options={
                'db_table': 'phieu_tra_hang_nhap',
            },
        ),
        migrations.CreateModel(
            name='PhieuXuatHuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('ghi_chu', models.TextField()),
            ],
            options={
                'db_table': 'phieu_xuat_huy',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.TextField()),
                ('ngay_them', models.DateField(auto_now_add=True)),
                ('gia_von', models.IntegerField(default=0)),
                ('gia_ban', models.IntegerField(default=0)),
                ('so_luong', models.IntegerField(default=0)),
                ('ton_kho', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('loai_hang', models.CharField(choices=[('RGV', 'Rau gia vị'), ('TC', 'Trái cây'), ('RAC', 'Rau ăn củ'), ('N', 'Nấm'), ('RAL', 'Rau ăn lá'), ('RCK', 'Các loại rau củ khác')], max_length=255)),
                ('mo_ta', models.TextField(blank=True)),
                ('nha_cung_cap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.NhaCungCap')),
            ],
            options={
                'db_table': 'san_pham',
            },
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='product',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='address',
            new_name='dia_chi',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='gender',
            new_name='gioi_tinh',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='district',
            new_name='ho_ten',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='first_name',
            new_name='huyen',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='salary',
            new_name='luong',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='birthday',
            new_name='ngay_sinh',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='phone',
            new_name='sdt',
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='last_name',
            new_name='tinh',
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='province',
        ),
        migrations.RemoveField(
            model_name='myusers',
            name='username',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='ImageProduct',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='phieuxuathuy',
            name='nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='phieutrahangnhap',
            name='nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='phieutrahangnhap',
            name='nha_cung_cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.NhaCungCap'),
        ),
        migrations.AddField(
            model_name='phieutra',
            name='khach_hang_tra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khach_hang_tra', to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='phieutra',
            name='nguoi_ban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_ban', to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='phieutra',
            name='nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_tao_phieu_tra', to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='nha_cung_cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.NhaCungCap'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='khach_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khach_hang', to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_tao_hoa_don', to='Store.MyUsers'),
        ),
        migrations.AddField(
            model_name='hinhanhsp',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='chitietphieuxuathuy',
            name='phieu_xuat_huy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.PhieuXuatHuy'),
        ),
        migrations.AddField(
            model_name='chitietphieuxuathuy',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='chitietphieutrahangnhap',
            name='phieu_tra_hang_nhap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.PhieuTraHangNhap'),
        ),
        migrations.AddField(
            model_name='chitietphieutrahangnhap',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='chitietphieutra',
            name='phieu_tra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phieu_tra', to='Store.PhieuTra'),
        ),
        migrations.AddField(
            model_name='chitietphieutra',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_pham_phieu_tra', to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='phieu_nhap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.PhieuNhap'),
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.SanPham'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='hoa_don',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don', to='Store.HoaDon'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='san_pham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='san_pham_hoa_don', to='Store.SanPham'),
        ),
    ]
