# Generated by Django 2.1.7 on 2019-03-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190319_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='username',
            field=models.CharField(default=0, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
