# Generated by Django 2.1.7 on 2019-05-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20190504_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangdat',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.TrangThaiHangHoa'),
        ),
    ]
