# Generated by Django 2.1.7 on 2019-03-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_myusers_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.TextField()),
            ],
            options={
                'db_table': 'loai_hang',
            },
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='loai_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.LoaiHang'),
        ),
    ]
