# Generated by Django 2.1.7 on 2019-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_hangdat_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='is_change',
            field=models.IntegerField(default=0),
        ),
    ]
