# Generated by Django 2.1.7 on 2019-05-08 15:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20190508_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='ngay_tao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2019, 5, 8, 15, 50, 52, 724834, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 5, 8, 15, 50, 52, 724798, tzinfo=utc)),
        ),
    ]
