# Generated by Django 2.1.7 on 2019-03-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_sanpham_avt'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
