# Generated by Django 2.1.7 on 2019-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_myusers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
