# Generated by Django 2.1.7 on 2019-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_myusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='avatar',
            field=models.FileField(default=0, upload_to='users/'),
            preserve_default=False,
        ),
    ]
