# Generated by Django 2.1.7 on 2019-04-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_myusers_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hanh_dong', models.TextField()),
                ('hoa_don', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_hoa_don', to='Store.HoaDon')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_tao', to=settings.AUTH_USER_MODEL)),
                ('phieu_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_phieu_nhap', to='Store.PhieuNhap')),
                ('phieu_tra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_phieu_tra', to='Store.PhieuTra')),
                ('phieu_tra_hang_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_phieu_tra_hang_nhap', to='Store.PhieuTraHangNhap')),
                ('phieu_xuat_huy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_phieu_xuat_huy', to='Store.PhieuXuatHuy')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='SoQuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tong_thu', models.IntegerField(default=0)),
                ('tong_chi', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'so_quy',
            },
        ),
    ]
