# Generated by Django 2.1.7 on 2019-04-12 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_log_soquy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='ghi_chu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='ngay_lap',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='ghi_chu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phieutrahangnhap',
            name='ghi_chu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phieuxuathuy',
            name='ghi_chu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='phieuxuathuy',
            name='thoi_gian_tao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
