# Generated by Django 2.1.7 on 2019-04-12 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_auto_20190412_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='HangDat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0)),
                ('check', models.IntegerField(default=0)),
                ('hang_dat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.SanPham')),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hang_dat',
            },
        ),
    ]
