# Generated by Django 2.1.7 on 2019-04-12 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_hangdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangdat',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
