# Generated by Django 2.1.7 on 2019-04-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_hangdat_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='ten_khach_hang',
            field=models.TextField(blank=True),
        ),
    ]
