# Generated by Django 2.1.7 on 2019-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_hoadon_ten_khach_hang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
