# Generated by Django 2.1.7 on 2019-04-14 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20190414_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='ngay_lap',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
