# Generated by Django 2.1.7 on 2019-04-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_auto_20190414_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
