# Generated by Django 2.1.7 on 2019-04-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_sanpham_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietphieunhap',
            name='phieu_nhap',
        ),
        migrations.RemoveField(
            model_name='chitietphieunhap',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='chitietphieutra',
            name='phieu_tra',
        ),
        migrations.RemoveField(
            model_name='chitietphieutra',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='chitietphieutrahangnhap',
            name='phieu_tra_hang_nhap',
        ),
        migrations.RemoveField(
            model_name='chitietphieutrahangnhap',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='chitietphieuxuathuy',
            name='phieu_xuat_huy',
        ),
        migrations.RemoveField(
            model_name='chitietphieuxuathuy',
            name='san_pham',
        ),
        migrations.RemoveField(
            model_name='phieunhap',
            name='nguoi_tao',
        ),
        migrations.RemoveField(
            model_name='phieunhap',
            name='nha_cung_cap',
        ),
        migrations.RemoveField(
            model_name='phieutra',
            name='khach_hang_tra',
        ),
        migrations.RemoveField(
            model_name='phieutra',
            name='nguoi_ban',
        ),
        migrations.RemoveField(
            model_name='phieutra',
            name='nguoi_tao',
        ),
        migrations.RemoveField(
            model_name='phieutrahangnhap',
            name='nguoi_tao',
        ),
        migrations.RemoveField(
            model_name='phieutrahangnhap',
            name='nha_cung_cap',
        ),
        migrations.RemoveField(
            model_name='phieuxuathuy',
            name='nguoi_tao',
        ),
        migrations.RemoveField(
            model_name='log',
            name='phieu_nhap',
        ),
        migrations.RemoveField(
            model_name='log',
            name='phieu_tra',
        ),
        migrations.RemoveField(
            model_name='log',
            name='phieu_tra_hang_nhap',
        ),
        migrations.RemoveField(
            model_name='log',
            name='phieu_xuat_huy',
        ),
        migrations.DeleteModel(
            name='ChiTietPhieuNhap',
        ),
        migrations.DeleteModel(
            name='ChiTietPhieuTra',
        ),
        migrations.DeleteModel(
            name='ChiTietPhieuTraHangNhap',
        ),
        migrations.DeleteModel(
            name='ChiTietPhieuXuatHuy',
        ),
        migrations.DeleteModel(
            name='PhieuNhap',
        ),
        migrations.DeleteModel(
            name='PhieuTra',
        ),
        migrations.DeleteModel(
            name='PhieuTraHangNhap',
        ),
        migrations.DeleteModel(
            name='PhieuXuatHuy',
        ),
    ]
