# Generated by Django 2.1.7 on 2019-04-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_auto_20190420_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrangThaiHoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_trang_thai', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
            ],
            options={
                'db_table': 'trang_thai',
            },
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='gia_ban',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='khuyen_mai',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='trang_thai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.TrangThaiHoaDon'),
        ),
    ]
