# Generated by Django 2.1.7 on 2019-04-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_auto_20190421_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trangthaihoadon',
            name='ten_trang_thai',
        ),
    ]
