# Generated by Django 2.1.7 on 2019-04-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_remove_trangthaihoadon_ten_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='trangthaihoadon',
            name='ma',
            field=models.CharField(default='pharse', max_length=200),
            preserve_default=False,
        ),
    ]
