# Generated by Django 2.1.7 on 2019-04-22 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_trangthaihoadon_ma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='hoa_don',
        ),
        migrations.RemoveField(
            model_name='log',
            name='nguoi_tao',
        ),
        migrations.AddField(
            model_name='hoadon',
            name='dia_chi',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoadon',
            name='sdt',
            field=models.CharField(default='hihi', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
