# Generated by Django 2.1.7 on 2019-04-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_auto_20190422_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='ngay_lap',
        ),
    ]
