# Generated by Django 2.1.5 on 2019-02-17 14:12

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongMua', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_hoa_don',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenHang', models.TextField(max_length=200, null=True)),
                ('soLuong', models.IntegerField(default=0)),
                ('donGiaNhap', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_phieu_nhap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuTra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongTra', models.IntegerField(default=0)),
                ('giaNhapLai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_phieu_tra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietTraHangNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuong', models.IntegerField(default=0)),
                ('giaTraLai', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_tra_hang_nhap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChiTietXuatHuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongHuy', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'chi_tiet_xuat_huy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maHang', models.CharField(max_length=200, null=True)),
                ('tenHang', models.TextField(max_length=200, null=True)),
                ('ngayNhap', models.DateTimeField(default=django.utils.timezone.now)),
                ('giaBan', models.IntegerField(default=0)),
                ('giaVon', models.IntegerField(default=0)),
                ('tonKho', models.IntegerField(default=0)),
                ('trangThai', models.CharField(max_length=200, null=True)),
                ('loaiHang', models.TextField(max_length=200, null=True)),
                ('soLuong', models.IntegerField(default=0)),
                ('hinhAnh', models.TextField(max_length=200, null=True)),
                ('moTa', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'hang_hoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maHoaDon', models.CharField(max_length=200, null=True)),
                ('thoiGianTao', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('ghiChu', models.TextField(max_length=200, null=True)),
                ('trangThai', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'hoa_don',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenKhachHang', models.TextField(max_length=200, null=True)),
                ('email', models.TextField(max_length=200, null=True)),
                ('dienThoai', models.CharField(max_length=200, null=True)),
                ('gioiTinh', models.TextField(max_length=200, null=True)),
                ('ngaySinh', models.DateField(verbose_name=datetime.date.today)),
                ('ngayTao', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('diaChi', models.TextField(max_length=200, null=True)),
                ('phuongXa', models.TextField(max_length=200, null=True)),
                ('huyen', models.TextField(max_length=200, null=True)),
                ('tinh', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'khach_hang',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maNhaCungCap', models.CharField(max_length=200, null=True)),
                ('tenNhaCungCap', models.TextField(max_length=200, null=True)),
                ('dienThoai', models.CharField(max_length=200, null=True)),
                ('email', models.TextField(max_length=200, null=True)),
                ('diaChi', models.TextField(max_length=200, null=True)),
                ('phuongXa', models.TextField(max_length=200, null=True)),
                ('huyen', models.TextField(max_length=200, null=True)),
                ('tinh', models.TextField(max_length=200, null=True)),
                ('trangThai', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'nha_cung_cap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maPhieu', models.CharField(max_length=200, null=True)),
                ('thoiGianNhap', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('ghiChu', models.TextField(max_length=200, null=True)),
                ('trangThai', models.CharField(max_length=200, null=True)),
                ('thoiGianTao', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'phieu_nhap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhieuTraHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maPhieu', models.CharField(max_length=200, null=True)),
                ('thoiGianTra', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('ghiChu', models.TextField(max_length=200, null=True)),
                ('trangThai', models.CharField(max_length=200, null=True)),
                ('khachHangTra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.KhachHang')),
            ],
            options={
                'db_table': 'phieu_tra_hang',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhieuTraHangNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maPhieu', models.CharField(max_length=200, null=True)),
                ('thoiGianTao', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('ghiChu', models.TextField(max_length=200, null=True)),
                ('trangThai', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'phieu_tra_hang_nhap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PhieuXuatHuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maXuatHuy', models.CharField(max_length=200, null=True)),
                ('thoiGianTao', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('thoiGianXuatHuy', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('ghiChu', models.TextField(max_length=200, null=True)),
                ('trangThai', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'phieu_xuat_huy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tenNhanVien', models.TextField(max_length=200, null=True)),
                ('luong', models.IntegerField(default=0)),
                ('dienThoai', models.CharField(max_length=200, null=True)),
                ('diaChi', models.TextField(max_length=200, null=True)),
                ('phuongXa', models.TextField(max_length=200, null=True)),
                ('huyen', models.TextField(max_length=200, null=True)),
                ('tinh', models.TextField(max_length=200, null=True)),
                ('email', models.TextField(max_length=200, null=True)),
                ('ngaySinh', models.DateField(verbose_name=datetime.date.today)),
                ('gioiTinh', models.TextField(max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'nhan_vien',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='phieuxuathuy',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phieutrahangnhap',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phieutrahangnhap',
            name='nhaCungCapTra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.NhaCungCap'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='nguoiBan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoiBan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoiTao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phieunhap',
            name='nhaCungCap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.NhaCungCap'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='khachHang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.KhachHang'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='nguoiTao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chitietxuathuy',
            name='hangHoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.HangHoa'),
        ),
        migrations.AddField(
            model_name='chitietxuathuy',
            name='xuatHuy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.PhieuXuatHuy'),
        ),
        migrations.AddField(
            model_name='chitiettrahangnhap',
            name='hangHoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.HangHoa'),
        ),
        migrations.AddField(
            model_name='chitiettrahangnhap',
            name='phieuTraHangNhap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.PhieuTraHangNhap'),
        ),
        migrations.AddField(
            model_name='chitietphieutra',
            name='maHang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.HangHoa'),
        ),
        migrations.AddField(
            model_name='chitietphieutra',
            name='phieuTra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageStore.PhieuTraHang'),
        ),
        migrations.AddField(
            model_name='chitietphieunhap',
            name='phieuNhap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.PhieuNhap'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='hangHoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageStore.HangHoa'),
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='hoaDon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageStore.HoaDon'),
        ),
    ]
