# Generated by Django 2.1.7 on 2019-02-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=200)),
                ('is_main', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='hanghoa',
            name='hinhAnh',
        ),
        migrations.AddField(
            model_name='anh',
            name='hangHoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManageStore.HangHoa'),
        ),
    ]
