# Generated by Django 2.1.5 on 2019-02-17 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='ngaySinh',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 17)),
        ),
    ]
