# Generated by Django 2.1.5 on 2019-02-17 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0002_auto_20190217_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhanvien',
            name='ngaySinh',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
