# Generated by Django 2.1.7 on 2019-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0002_auto_20190227_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anh',
            name='path',
            field=models.FileField(upload_to='ImageProducts'),
        ),
    ]
