# Generated by Django 2.1.7 on 2019-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0003_auto_20190228_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='anh',
            name='tenAnh',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
