# Generated by Django 2.1.7 on 2019-02-28 17:11

import ManageStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageStore', '0004_anh_tenanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anh',
            name='path',
            field=models.FileField(upload_to=ManageStore.models.Anh.path_and_rename),
        ),
    ]
